// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScndMVC.Models;

namespace ScndMVC.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20250508041510_V1.1")]
    partial class V11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ScndMVC.Models.Agendamento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DtDia")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DtModificao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FuncionarioID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HrAgendamento")
                        .HasColumnType("time(6)");

                    b.Property<int>("IdCriador")
                        .HasColumnType("int");

                    b.Property<int?>("IdModificador")
                        .HasColumnType("int");

                    b.Property<string>("NmCliente")
                        .IsRequired()
                        .HasColumnType("varchar(63) CHARACTER SET utf8mb4")
                        .HasMaxLength(63);

                    b.Property<int>("ServicoID")
                        .HasColumnType("int");

                    b.Property<int>("Stats")
                        .HasColumnType("int");

                    b.Property<float?>("Valor")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("FuncionarioID");

                    b.HasIndex("ServicoID");

                    b.ToTable("Agendamento");
                });

            modelBuilder.Entity("ScndMVC.Models.Configuracao", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AgendaMultipla")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Domingo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DtModificao")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("HrFim")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HrInicio")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HrPausaFim")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HrPausaInicio")
                        .HasColumnType("time(6)");

                    b.Property<int>("IdCriador")
                        .HasColumnType("int");

                    b.Property<int?>("IdModificador")
                        .HasColumnType("int");

                    b.Property<int>("PeriodoAtendimento")
                        .HasColumnType("int");

                    b.Property<bool>("Quarta")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Quinta")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Sabado")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Segunda")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Sexta")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Terca")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID");

                    b.ToTable("Configuracao");
                });

            modelBuilder.Entity("ScndMVC.Models.Funcionario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Administrador")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ConfiguracaoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DtModificao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("IdCriador")
                        .HasColumnType("int");

                    b.Property<int?>("IdModificador")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("varchar(31) CHARACTER SET utf8mb4")
                        .HasMaxLength(31);

                    b.Property<string>("NmProfissional")
                        .IsRequired()
                        .HasColumnType("varchar(63) CHARACTER SET utf8mb4")
                        .HasMaxLength(63);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(15) CHARACTER SET utf8mb4")
                        .HasMaxLength(15);

                    b.HasKey("ID");

                    b.HasIndex("ConfiguracaoID");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("ScndMVC.Models.Servico", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DsServico")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DtModificao")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FuncionarioID")
                        .HasColumnType("int");

                    b.Property<int>("IdCriador")
                        .HasColumnType("int");

                    b.Property<int?>("IdModificador")
                        .HasColumnType("int");

                    b.Property<string>("NmServico")
                        .IsRequired()
                        .HasColumnType("varchar(63) CHARACTER SET utf8mb4")
                        .HasMaxLength(63);

                    b.Property<float>("Valor")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("FuncionarioID");

                    b.ToTable("Servico");
                });

            modelBuilder.Entity("ScndMVC.Models.Agendamento", b =>
                {
                    b.HasOne("ScndMVC.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScndMVC.Models.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScndMVC.Models.Funcionario", b =>
                {
                    b.HasOne("ScndMVC.Models.Configuracao", "Configuracao")
                        .WithMany()
                        .HasForeignKey("ConfiguracaoID");
                });

            modelBuilder.Entity("ScndMVC.Models.Servico", b =>
                {
                    b.HasOne("ScndMVC.Models.Funcionario", null)
                        .WithMany("Servicos")
                        .HasForeignKey("FuncionarioID");
                });
#pragma warning restore 612, 618
        }
    }
}
